config/routes.rb
Rails.application.routes.draw do
  # Session
  root 'session#login'
  get 'signout', to: 'session#logout', as: :logout
  post 'signup', to: 'session#create'

  resources :user do
		collection do
			post 'password'
		end 
	end
  
  resources :medication do
		collection do
			get 'autocomplete'
		end 
	end
	get 'medications', to: 'medication#medications', as: 'medications'

	resources :treatment do
		collection do
			put 'last_taken'
		end 
	end

	get 'recover', to: 'account#recover', as: 'recover'
	post 'password_reset', to: 'account#password', as: 'password_reset'

end

app/models/frequency.rb
class Frequency < ActiveRecord::Base
	has_many :treatments
end

app/models/medication.rb
class Medication < ActiveRecord::Base
	has_many :treatments

	default_scope { order(name: :asc) }

	def self.search(query)
		where("name like ?", "%#{query}%")
	end
end

app/models/medication_type.rb
class MedicationType < ActiveRecord::Base
	has_many :treatments
end

app/models/password_reminder.rb
class PasswordReminder < ActiveRecord::Base
  belongs_to :user
end

app/models/treatment.rb
class Treatment < ActiveRecord::Base
	belongs_to :user
	belongs_to :medication
	belongs_to :medication_type
	belongs_to :unit
	belongs_to :frequency

	validates :user_id, presence: true
	validates :medication_id, presence: true
	validates :frequency_id, presence: true
	validates :frequency_quantity, presence: true
	validates :start, presence: true
	validates :finish, presence: true
	validates :hour, presence: true
end

app/models/unit.rb
class Unit < ActiveRecord::Base
	has_many :treatments
end

app/models/user.rb
class User < ActiveRecord::Base

	# Relationships
	has_many :treatments

	# Bcrypt
	has_secure_password

	# Validations
	validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@([^@.\s]+\.)+[^@.\s]+\z/ }
	validates :password, length: {minimum: 6}


end

app/controllers/account_controller.rb
class AccountController < ApplicationController

	def recover
	end

	def password
		@user = User.find_by_email(params[:email])
		@new_password = SecureRandom.base64(6)
		@user.password =  @new_password
		if @user.save
			Medimailer.recover_account_email(@user,@new_password).deliver
		end
		redirect_to root_path
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  # Get session user
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]

  end
  helper_method :current_user

  # Validate user session
  def validate_user
    redirect_to '/' unless current_user
  end

  def validate_session
    redirect_to '/treatment' if current_user
  end

  def validate_admin
    if current_user.role == 0
      redirect_to '/treatment'
    end
  end

  protected

  # --------Filters--------

  # device OS detection. Class Variables will be used on views to define which CSS one should render
  def detect_mobile
    case request.user_agent
    when /Mobile/
      case request.user_agent
      when /iPhone/
        @iphone = true
      when /Android/
        @android = true
      when /Windows Phone/
        @windows = true
      end
    end
    unless @iphone || @android || @windows
      @android = true
    end
  end
end

app/controllers/medication_controller.rb
class MedicationController < ApplicationController

	before_action :detect_mobile, :validate_user
  before_action :validate_admin, except: [:medications, :autocomplete]
  # GET /medications
  # GET /medications.json
  def index
    @medications = Medication.all
  end

  # GET /medications/1
  # GET /medications/1.json
  def show
  end

	# GET /medications/new	
	def new

		@medication = Medication.new

	end


  # GET /medications/1/edit
  def edit
  
  end

  # POST /medications
  # POST /medications.json
  def create
    @medication = Medication.new(medication_params)

    if @medication.save
      redirect_to controller: :medication, action: :index
    else
      redirect_to controller: :medication, action: :index
    end

  end

  # PATCH/PUT /medications/1
  # PATCH/PUT /medications/1.json
  def update
    respond_to do |format|
      if @medication.update(medication_params)
        format.html { redirect_to @medication, notice: 'Medication was successfully updated.' }
        format.json { render :show, status: :ok, location: @medication }
				# redirect_to controller: :nombre_controller, action: :nombre_action
      else
        format.html { render :edit }
        format.json { render json: @medication.errors, status: :unprocessable_entity }
				# redirect_to controller: :nombre_controller, action: :nombre_action
      end
    end
  end

  # DELETE /medications/1
  # DELETE /medications/1.json
  def destroy
    respond_to do |format|
      if Medication.find(params[:id]).destroy
        format.json { render status: :ok, json:"Medication Deleted." }
      else
        format.json { render status: :bad_request, json: "Medication couldnt be deleted" }
      end
    end
  end

  def autocomplete
    respond_to do |format|
      meds = Medication.search(params[:q])
      format.json { render status: :ok, json: meds.to_json }
    end
  end

  def medications
    @medications = Medication.all
  end

	private
    # Use callbacks to share common setup or constraints between actions.
		def set_medication
			@medication = Medication.find(params[:id])
		end

		def medication_params
			params.require(:medication).permit(:name, :description)
		end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController

	before_action :validate_session, only: [:login]

	def login
		# login view
	end

	def logout
		session.delete(:user_id)
    	redirect_to '/'
	end

	# POST. Create new session
	def create
		user = User.find_by_email(params[:session][:email])

	    # If the user exists AND the password entered is correct.
	    if user && user.authenticate(params[:session][:password])
	      	session[:user_id] = user.id
			redirect_to controller: :treatment, action: :index
	    else
	    	redirect_to root_path
	    end
	end

end

app/controllers/treatment_controller.rb
class TreatmentController < ApplicationController

	before_action :validate_user

	def index
  		@treatments = current_user.treatments
  	end

  	def new
		@treatment = Treatment.new
	end

  	def create
		@treatment = Treatment.new(treatment_params)
		@treatment.start = params[:treatment][:start].to_date.strftime("%Y-%m-%d")
		@treatment.finish = params[:treatment][:start].to_date.strftime("%Y-%m-%d")
		if @treatment.save
			redirect_to controller: :treatment, action: :index
		else
			redirect_to controller: :treatment, action: :index
		end
	end

	def destroy
		respond_to do |format|
			if Treatment.find(params[:id]).destroy
				format.json { render status: :ok, json:"Treatment Deleted." }
			else
				format.json { render status: :bad_request, json: "Treatment couldnt be deleted" }
			end
	    end
	end

	def last_taken
		@treatment = Treatment.find(params[:id])
		if @treatment.touch
			redirect_to controller: :treatment, action: :index
		else
			redirect_to controller: :user, action: :edit
		end

	end

	private

	def treatment_params
		params.require(:treatment).permit(:start, :finish, :hour, :frequency_quantity, :frequency_id, :user_id, :medication_id)
	end

end

app/controllers/user_controller.rb
class UserController < ApplicationController

	before_action :detect_mobile
	
	def new

		@user = User.new
	end

	def create

		user = User.new(user_params)

		if user.save
			Medimailer.send_signup_email(user).deliver
			redirect_to root_path			
		else
			redirect_to root_path
		end
		
	end

	def edit
		@user = current_user
	end

	def update
		@user = current_user
		if @user.update(update_params)
			redirect_to controller: :user, action: :edit
		else
			flash[:errors] = @user.errors.full_messages
			redirect_to controller: :user, action: :edit
		end
	end

	def password
		@user = current_user
		if @user.update(password_params)
			redirect_to controller: :user, action: :edit
		else
			redirect_to controller: :user, action: :edit
		end
	end

	private

	def user_params
		params.require(:user).permit(:email, :name, :password, :password_confirmation)

	end

	def update_params
		params.permit(:email, :name, :password, :password_confirmation)

	end

end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/treatment_helper.rb
module TreatmentHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

	<meta charset="utf-8">
	<meta content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="mobile-web-app-capable" content="yes">
	<meta name="msapplication-tap-highlight" content="no">

  <title>MediApp | <%= @title%></title>
  <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag 'chui-ios-3.8.1.min', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag params[:controller] %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>


<%if request.env['PATH_INFO'] != "/" && current_user%>
  <footer>

    <ul>
      <li>
        <%if current_user.role == 0%>
        <a href="/medications"><span class="icon-medical56"></span></a>
        <%else%>
        <a href="/medication"><span class="icon-medical56"></span></a>
        <%end%>
        <br>
        <span>Meds</span>
        </li>
      <li>
        <a href="/treatment"><span class="icon-home3"></span></a>
        <br>
        <span>Home</span>
      </li>
      <li>
        <a href="/user/<%=session[:user_id]%>/edit"><span class="icon-user"></span></a>
        <br>
        <span>Profile</span>
      </li>
      <li>
        <a href="/signout"><span class="icon-sign-out"></span></a>
        <br>
        <span>Sign out</span>
      </li>
    </ul>
  </footer>
<%end%>
</body>
</html>

app/views/medication/index.html.erb
<nav class="current">
	<h1>Meds</h1>
	<button class='button align-flush' id='addMedication'><span class="text-green icon-plus"></span></button>
</nav>
 <article id="medication" class="current">
	<section>
		<ul class='list' id="medication-list">
			<% @medications.each do |med| %>
		    <li class='comp text-center' data-id="<%= med.id %>">
		        <div>
		            <h3 class="text-black"><strong><%= med.name %></strong></h3>
		            <p class="text-grey"><%= med.description %></p>
		        </div>
		        <aside>
		            <span class='nav'></span>
		        </aside>
		    </li>
		    <%end%>
		</ul>
	</section>
</article>

<nav class="next">
	<a class='button back text-green'>Cancel</a>
	<h1>Add Medication</h1>
</nav>
<article id="newMedication" class="next">
	<section>
	<br>
		<%= form_for :medication, url: {action: "create"}, html: { class: "ui-filterable text-center"} do |f| %>

			<%= f.text_field :name, placeholder: "Name" %>
			<%= f.text_field :description, placeholder: "Description" %>
			<br/>
			<br/>
			<%= f.submit "Add Medication", class:"btn btn-green"%>
		<% end %>
	</section>
</article>

app/views/medication/medications.html.erb
<nav class="current">
	<h1>Meds</h1>
</nav>
 <article id="public-meds" class="current">
	<section>
		<ul class='list' id="medication-list">
			<% @medications.each do |med| %>
		    <li class='comp text-center' data-id="<%= med.id %>">
		        <div>
		            <h3 class="text-black"><strong><%= med.name %></strong></h3>
		            <p class="text-grey"><%= med.description %></p>
		        </div>
		        <aside>
		            <span class='nav'></span>
		        </aside>
		    </li>
		    <%end%>
		</ul>
	</section>
</article>

app/views/session/login.html.erb
<nav class="current">
	<h1>Welcome!</h1>
 </nav>
<article id="sign-in" class="current">
	<section>
		<h1 class="text-center text-green">Medi<strong class="text-black">App</strong><span class="icon-medical10"></span></h1>
		<%= form_for :session, url: {action: "create"}, html: { class: "text-center"} do |f| %>
			<%= f.email_field :email , placeholder:"Email Address"%>
			<%= f.password_field :password, placeholder:"Password" %>
			<%= f.submit "sign in", class:"btn btn-green"%>
			<br/>
			<br/>
			<a class='btn text-green btn-block' href="<%=new_user_path%>">Sign Up</a>
			<a href="<%=recover_path%>" class="btn text-green btn-block">Recover Account</a>
		<% end %>
	</section>
</article>

app/views/treatment/index.html.erb
<nav class="current">
	<h1>Home</h1>
	<button class='button align-flush' id='addButton'><span class="text-green icon-plus"></span></button>
</nav>
 <article id="index" class="current">
	<section>
		<ul class='list' id="med-list">
			<% @treatments.each do |treatment| %>
		    <li class='comp' data-id="<%= treatment.id%>">
		        <div>
		            <span class="icon-checkmark"></span>
		            <h3 class="text-black"><strong><%= treatment.medication.name %></strong></h3>
		            <p class="text-grey">Last taken: <%= treatment.updated_at.strftime('%Y-%m-%d %I:%m %p') %></p>
		        </div>
		    </li>
		    <%end%>
		</ul>
	</section>
</article>

<nav class="next">
	<a class='button back text-green'>Cancel</a>
	<h1>Add Treatment</h1>
</nav>
<article id="newTreatment" class="next">
	<section>
		<%= form_for :treatment, url: {action: "create"}, html: { class: "ui-filterable text-center"} do |f| %>

			<input autocomplete="off" id="autocomplete-input" data-type="search" placeholder="Find a medication">
			<ul id="autocomplete" data-role="listview" data-inset="true" data-filter="true" data-input="#autocomplete-input"></ul>
			<%= f.hidden_field :medication_id%>

			<ul class="list-inline">
				<li class="col-half">
					<div class="padding-right">
						<%= f.select(:frequency_quantity,1..10, {prompt: "Every..."}) %>
					</div>
				</li>
				<li class="col-half">
					<div class="padding-left">
						<%= f.collection_select(:frequency_id, Frequency.all, :id, :value,:prompt => "Select a frecuency") %>
					</div>	
				</li>
				<div class="clearfix"></div>
			</ul>
			
			<%= f.text_field :start, class: "pickdate", placeholder: "Start date"%>
			<%= f.text_field :finish, class: "pickdate", placeholder: "Finish date"%>
			<%= f.text_field :hour, class: "picktime", placeholder: "Start hour"%>
			<%= f.hidden_field :user_id, value: session[:user_id]%>
			<br/>
			<br/>
			<%= f.submit "Add Treatment", class:"btn btn-green"%>
		<% end %>
	</section>
</article>

app/views/user/edit.html.erb
<nav class="current">
	<h1>Profile</h1>
</nav>
<article id="details" class="current">
	<section>
	<%=flash[:errors]%>
	<br>
		<%= form_tag({controller: "user", action: "update"}, method: "put") do %>
			<%= text_field_tag 'name', @user.name, placeholder: "Name" %>
			<%= email_field_tag 'email', @user.email, placeholder: "Email"  %>
			<%= password_field_tag :password, nil, placeholder: "Password" %>
			<%= password_field_tag :password_confirmation,nil, placeholder: "Password Confirmation" %>
			<br/>
			<br/>
			<%= submit_tag "Update", class:"btn btn-green"%>
		<% end %>
	</section>
</article>

app/views/user/new.html.erb
<nav class="current">
	<h1>Sign up</h1>
</nav>
<article id="sign-up" class="current">
	<section>
		<h1 class="text-center text-green">Medi<strong class="text-black">App</strong><span class="icon-medical10"></span></h1>
		<%= form_for :user, url: {action: "create"}, html: { class: "text-center"} do |f| %>
			<%= f.email_field :email , placeholder:"Email Address"%><br/>
			<%= f.text_field :name , placeholder:"User Name"%><br/>
			<%= f.password_field :password, placeholder:"Password" %><br/>
			<%= f.password_field :password_confirmation, placeholder: "Password Confirmation" %><br/>
			<%= f.submit "create account", class:"btn btn-green"%>
		<% end %>
		<br/>
		<br/>
		<div class="text-center">
			<a class='btn text-green btn-block' href="<%=root_path%>">Sign In</a>
			<a href="<%=root_path%>" class="btn text-green btn-block">Recover Account</a>
		</div>
	</section>
</article>